# Generated by Django 5.2.11 on 2026-02-26 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('GENERATION', 'Generation'), ('REFUND', 'Refund'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('content_type', models.CharField(blank=True, choices=[('PAGE', 'Page'), ('COVER', 'Cover'), ('CHARACTER', 'Character')], max_length=20, null=True)),
                ('content_id', models.UUIDField(blank=True, help_text='PageVersion, CoverVersion, or CharacterVersion ID', null=True)),
                ('attempt_number', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_consumed', models.BooleanField(default=False)),
                ('nano_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GEL', max_length=10)),
                ('max_retries_per_unit', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GEL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('provider_payment_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
