# Generated by Django 5.2.11 on 2026-02-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='retry_consumed',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.purchase'),
        ),
    ]
