# Generated by Django 5.2.11 on 2026-02-26 16:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('ua_hash', models.CharField(max_length=64)),
                ('character_creations', models.PositiveIntegerField(default=0)),
                ('character_generations', models.PositiveIntegerField(default=0)),
                ('cover_generations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='For anonymous book before login', max_length=40, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('art_style', models.CharField(max_length=100)),
                ('style_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('LOCKED', 'Locked'), ('ORDERED', 'Ordered'), ('PRINTED', 'Printed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('total_pages', models.IntegerField(default=0)),
                ('last_generation_at', models.DateTimeField(blank=True, null=True)),
                ('print_size', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=50, null=True)),
                ('binding_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_print_ready', models.BooleanField(default=False)),
                ('print_locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_consistency_verified', models.BooleanField(default=False)),
                ('total_images_generated', models.PositiveIntegerField(default=0)),
                ('total_generation_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_anon_token', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('reference_photo', models.ImageField(upload_to='characters/reference/')),
                ('total_generation_attempts', models.IntegerField(default=0)),
                ('free_retry_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='products.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('generated_image', models.ImageField(upload_to='characters/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('prompt_snapshot', models.JSONField()),
                ('aspect_ratio', models.CharField(max_length=20)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('generation_job_id', models.UUIDField()),
                ('generation_cost_usd', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nano_request_id', models.CharField(blank=True, max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.character')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.ledgerentry')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.characterversion'),
        ),
        migrations.CreateModel(
            name='CoverVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_anon_token', models.UUIDField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('title_text', models.CharField(max_length=255)),
                ('subtitle_text', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title_position', models.JSONField(blank=True, null=True)),
                ('generated_image', models.ImageField(upload_to='covers/')),
                ('full_spread_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('prompt_snapshot', models.JSONField()),
                ('aspect_ratio', models.CharField(max_length=20)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('generation_job_id', models.UUIDField()),
                ('generation_cost_usd', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('nano_request_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_versions', to='products.book')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_versions', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.ledgerentry')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='current_cover_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.coverversion'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('scene_description', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='products.book')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('nano_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('generation_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.ledgerentry')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.page')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.pageversion'),
        ),
        migrations.CreateModel(
            name='RetryAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('CHARACTER', 'Character'), ('COVER', 'Cover'), ('PAGE', 'Page')], max_length=20)),
                ('content_id', models.UUIDField()),
                ('max_retries', models.PositiveIntegerField(default=0)),
                ('used_retries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_allowances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='characterversion',
            index=models.Index(fields=['character', 'created_at'], name='products_ch_charact_5d5306_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='characterversion',
            unique_together={('character', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='coverversion',
            unique_together={('book', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', 'status'], name='products_bo_user_id_c56f52_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', '-created_at'], name='products_bo_user_id_875dc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='pageversion',
            index=models.Index(fields=['page', 'created_at'], name='products_pa_page_id_3603e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageversion',
            unique_together={('page', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('book', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='retryallowance',
            index=models.Index(fields=['user', 'content_type', 'content_id'], name='products_re_user_id_b212e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retryallowance',
            unique_together={('user', 'content_type', 'content_id')},
        ),
    ]
