# Generated by Django 5.2.11 on 2026-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousprofile',
            name='book_creations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverversion',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
