# Generated by Django 5.2.12 on 2026-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_generated_image_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='coverversion',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
