# Generated by Django 5.2.12 on 2026-03-12 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_character_gender_alter_coverversion_aspect_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterReferencePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='characters/reference/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_photos', to='products.character')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
